accounts/urls.py
from django.conf.urls import url
from .import views

app_name = 'accounts'

urlpatterns = [
    url(r'^$', views.home, name='accounts-home'),
    url(r'^update/$', views.update, name='accounts-update'),
    url(r'^create/$', views.UserFormView.as_view(), name='accounts-create'),
    url(r'^login/$', views.login_view, name='accounts-login'),
    url(r'^logout/$', views.logout_view, name='accounts-logout'),
]

contests/urls.py
from django.conf.urls import url
from .import views

app_name = 'contests'

urlpatterns = [
    url(r'^$', views.index, name='contests-home'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='contest-detail'),
    url(r'^(?P<pk>[0-9]+)/ranklist/$', views.getranklist, name='contest-ranklist'),
    url(r'^(?P<contest_id>[0-9]+)/problem/(?P<pk>[0-9]+)/$', views.problem_page, name='contest-problem'),
]

home/urls.py
from django.conf.urls import url
from .import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.show_home, name='home'),
]

practice/urls.py
from django.conf.urls import url
from .import views

app_name = 'practice'

urlpatterns = [
    url(r'^$', views.practice_problems, name='practice-home'),
    url(r'^problem/(?P<pk>[0-9]+)/$', views.practice_problem_page, name='practice-problem'),
]

swagrader/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^home/', include('home.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^contests/', include('contests.urls')),
    url(r'^practice/', include('practice.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contests/models.py
from django.db import models
from django.urls import reverse
from accounts.models import Profile
from django.contrib.auth.models import User


# Create your models here.


class Challenge(models.Model):
    """ Model to Represent a Single Contest """
    challenge_code = models.CharField(max_length=50)
    challenge_name = models.CharField(max_length=50)
    Active, Upcoming, Past = 'Active', 'Upcoming', 'Past'
    Status_Choices = ((Active, 'Active'), (Upcoming, 'Upcoming'), (Past, 'Past'))
    status = models.CharField(max_length=20, choices=Status_Choices, default=Upcoming)

    # Add Questions field

    def __str__(self):
        return self.challenge_name

    def get_absolute_url(self):
        return reverse('contests:details',
                       kwargs={'pk': self.pk})  # detail view requires primary key so we send in the key like that


class Problem(models.Model):
    """ Model to represent a single problem """
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE, default=None)
    problem_code = models.CharField(max_length=50)
    problem_name = models.CharField(max_length=50)
    problem_file_url = models.CharField(max_length=50)
    in_practice = models.BooleanField(default=False)
    score = models.IntegerField(default=100)

    def __str__(self):
        return self.problem_code

    def get_absolute_url(self):
        return reverse('contests:contest-detail', kwargs={'pk': self.challenge.pk})  # detail view requires primary
        # key so we send in the key like that


class Submission(models.Model):
    """ Model to Represent a submission by a user to a particular problem """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    cpp, c, python = 'cpp', 'c', 'python'
    language_choices = ((cpp, 'cpp'), (c, 'c'), (python, 'python'))
    language = models.CharField(max_length=20, choices=language_choices, default=None)
    CK, AC, WA, TLE, RE, CTE = 'Checking', 'Accepted', 'Wrong Answer', 'Time Limit Exceeded', 'Runtime Error', \
                               'Compile Time Error'
    status_choices = ((AC, 'Accepted'), (WA, 'Wrong Answer'), (TLE, 'Time Limit Exceeded'), (RE, 'Runtime Error'),
                      (CTE, 'Compile Time Error'), (CK, 'Checking'))
    status = models.CharField(max_length=20, choices=status_choices, default=CK)
    source_file = models.FileField()
    score_achieved = models.IntegerField(default=0, null=True)

    def __str__(self):
        return self.user.username + '__' + self.problem.problem_code + '__' + self.status

contests/views.py
from django.shortcuts import render
from django.views import generic
from .models import *
from judge import falcon


# Create your views here.


def index(request):
    """ To display list of all active, upcoming and Past Contests """
    active = Challenge.objects.filter(status='Active')
    upcoming = Challenge.objects.filter(status='Upcoming')
    past = Challenge.objects.filter(status='Past')
    context = {
        'active': active,
        'upcoming': upcoming,
        'past': past,
        'current_user': None,
    }
    if request.user.is_authenticated:
        context['current_user'] = request.user
    return render(request, 'contests/index.html', context)


class DetailView(generic.DetailView):
    """ To Display list of problems in a Contest """
    model = Challenge
    template_name = 'contests/contest_page.html'
    context_object_name = 'contest'


def problem_page(request, contest_id, pk):
    problem_id = pk
    context = {
        'current_user': None,
        'current_challenge': Challenge.objects.get(pk=contest_id),
        'problem': Problem.objects.get(pk=problem_id),
    }
    if request.user.is_authenticated:
        context['current_user'] = request.user

    if request.method == 'GET':
        # Display a single problem
        return render(request, 'contests/prob-placeholder.html', context)

    elif request.method == 'POST':
        # Code Submission and Evaluation
        submission = Submission()
        submission.user = request.user
        submission.problem = Problem.objects.get(pk=problem_id)
        submission.language = request.POST['language-choice']
        submission.source_file = request.FILES['src-file']
        submission.status = 'Checking'
        submission.save()

        result = falcon.eval_submission(
            problem_code=submission.problem.problem_code,
            src_file_name=submission.source_file.name,
            language=submission.language
        )
        submission.status = context['response'] = result[0]
        if submission.status == 'Accepted':
            submission.score_achieved = submission.problem.score
        submission.save()
        return render(request, 'contests/sub_response.html', context)


def getranklist(request, pk):
    challenge = Challenge.objects.get(id=pk)
    all_acc_subs = Submission.objects.filter(problem__challenge__id=pk, status='Accepted')
    prob_codes = [each.problem_code for each in challenge.problem_set.all()]
    users = set([each.user for each in all_acc_subs])
    
    ranklist = []
    for user in users:
        score_card = {'user': user.username, 'total': 0}
        for prob in prob_codes:
            found = False
            for sub in all_acc_subs:
                if sub.problem.problem_code == prob and sub.user == user:
                    found = True
                    score_card[prob] = sub.score_achieved
                    break
            if not found:
                score_card[prob] = 0
        for prob in prob_codes:
            score_card['total'] += score_card[prob]
        ranklist.append(score_card)

    ranklist.sort(reverse=True, key=lambda x : x['total'])
    columns = ['Username'] + prob_codes + ['Total']
    context = {
        'ranklist': ranklist,
        'column_header': columns,
    }
    return render(request, 'contests/ranklist.html', context)

contests/templates/contests/contest_page.html
{% extends 'accounts/base.html' %}
{% block title %}
    Challenge
{% endblock %}

{% block body %}
    <ul>
        {% for problem in contest.problem_set.all %}
            <li>
                <a href="{% url 'contests:contest-problem' contest.id problem.id %}">{{ problem }}</a>
            </li>
        {% endfor %}
    </ul>
    <br>
    <a href="{% url 'contests:contest-ranklist' contest.id %}">Get Ranklist</a>
{% endblock %}

contests/templates/contests/index.html
{% extends 'accounts/base.html' %}
{% block title %}
    Challenges
{% endblock %}

{% block navbar %}
    <ul class="nav navbar-nav">
        <li><a href="{% url 'home:home' %}">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="{% url 'practice:practice-home' %}">Practice</a></li>
        <li class="active"><a href="{% url 'contests:contests-home' %}">Contests</a></li>
    </ul>
    {% if not current_user %}
        <ul class="nav navbar-nav navbar-right">

        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" ><span class="glyphicon glyphicon-log-in"></span>
                Login
            </a>
            <ul class="dropdown-menu">
                <li>
                    <form action="{% url 'accounts:accounts-login' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <label for="user_name">Username</label><br>
                        <input type="text" id="user_name" name="username"><br>
                        <label for="password">Password</label><br>
                        <input type="password" id="password" name="password"><br>
                        <input type="submit" name="log-in" value="Log In">
                    </form>
                </li>
            </ul>
        </li>

        <li><a href="{% url 'accounts:accounts-create' %}"><span class="glyphicon glyphicon-grain"></span>SignUp</a></li>
        </ul>
    {% else %}
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" ><span class="glyphicon glyphicon-user"></span>
                    {{ current_user.username }}<span class="caret"></span>
                    </a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'accounts:accounts-home' %}">Profile</a></li>
                  <li><a href="{% url 'accounts:accounts-logout' %}">Logout</a></li>
                </ul>
            </li>
        </ul>
    {% endif %}
{% endblock %}


{% block body %}

    <div class="container-fluid text-center">
        <div class="row content">
            <div class="col-sm-2 sidenav">
                <p><a href="#">Motivation</a></p>
                <p><a href="#">Vision</a></p>
                <p><a href="#">Future</a></p>
                <p><a href="#">History</a></p>
            </div>
            <div class="col-sm-9 text-left">
                <h4>Active Contests</h4>
                <ul>
                    {% for each in active %}
                        <li><a href="{% url 'contests:contest-detail' each.pk %}">{{ each }}</a></li>
                    {% endfor %}
                </ul>
                <br><br>
                <h4>Upcoming Contests</h4>
                <ul>
                    {% for each in upcoming %}
                        <li><a href="{% url 'contests:contest-detail' each.pk %}">{{ each }}</a></li>
                    {% endfor %}
                </ul>
                <br><br>
                <h4>Past Contests</h4>
                <ul>
                    {% for each in past %}
                        <li><a href="{% url 'contests:contest-detail' each.pk %}">{{ each }}</a></li>
                    {% endfor %}
                </ul>
                <br><br>

            </div>
        </div>
    </div>

{% endblock %}

contests/templates/contests/prob-placeholder.html
{% extends 'accounts/base.html' %}
{% block title %}
    Problem
{% endblock %}

{% block body %}
    <h5>Problems for {{ current_challenge }} </h5><br>
    {% include problem.problem_file_url %}
    {% if current_user %}
        <br>
        <h6>Submission</h6>
         <form action="" method="post" enctype="multipart/form-data">
             {% csrf_token %}
             <label for="language">Language</label>
             <select id="language" name="language-choice">
                 <option value="cpp">cpp</option>
                 <option value="c">c</option>
                 <option value="python">python</option>
             </select>
             <br>
             <label for="source-code">Upload File</label>
             <input type="file" id="source-code" name="src-file">
             <br>
             <input type="submit" value="Submit">
         </form>
    {% else %}
        Login To submit
    {% endif %}
{% endblock %}

contests/templates/contests/ranklist.html
{% extends 'accounts/base.html' %}
{% block title %}
    Ranklist
{% endblock %}

{% block body %}
    Ranklist here
    <br><br>
    {{ ranklist }}
{% endblock %}

contests/templates/contests/sub_response.html
{% extends 'accounts/base.html' %}
{% block title %}
    Response
{% endblock %}

{% block body %}
    {% if current_user %}
        <h5>User Logged in : {{ current_user }}</h5><br>
        <h5>{{ problem }} from {{ current_challenge }}</h5><br>
        <h5>Submission Status : {{ response }} </h5>
    {% else %}
        <h5>Not Authorized</h5>
    {% endif %}
{% endblock %}