accounts/urls.py
from django.conf.urls import url
from .import views

app_name = 'accounts'

urlpatterns = [
    url(r'^$', views.home, name='accounts-home'),
    url(r'^update/$', views.update, name='accounts-update'),
    url(r'^create/$', views.UserFormView.as_view(), name='accounts-create'),
    url(r'^login/$', views.login_view, name='accounts-login'),
    url(r'^logout/$', views.logout_view, name='accounts-logout'),
]

contests/urls.py
from django.conf.urls import url
from .import views

app_name = 'contests'

urlpatterns = [
    url(r'^$', views.index, name='contests-home'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='contest-detail'),
    url(r'^(?P<pk>[0-9]+)/ranklist/$', views.getranklist, name='contest-ranklist'),
    url(r'^(?P<contest_id>[0-9]+)/problem/(?P<pk>[0-9]+)/$', views.problem_page, name='contest-problem'),
]

home/urls.py
from django.conf.urls import url
from .import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.show_home, name='home'),
]

practice/urls.py
from django.conf.urls import url
from .import views

app_name = 'practice'

urlpatterns = [
    url(r'^$', views.practice_problems, name='practice-home'),
    url(r'^problem/(?P<pk>[0-9]+)/$', views.practice_problem_page, name='practice-problem'),
]

swagrader/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^home/', include('home.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^contests/', include('contests.urls')),
    url(r'^practice/', include('practice.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

practice/models.py
from django.db import models

# Create your models here.

practice/views.py
from django.shortcuts import render
from contests.models import Problem, Submission
from judge import falcon
from swagrader.settings import BASE_DIR
# Create your views here.


def practice_problems(request):
    """ Display all Practice Problems """
    context = {
        'problems': Problem.objects.filter(in_practice=True),
        'current_user': None,
    }
    if request.user.is_authenticated:
        context['current_user'] = request.user
    return render(request, "practice/practice-section.html", context)


def practice_problem_page(request, pk):
    problem_id = pk
    context = {
        'current_user': None,
        'current_challenge': 'Practice',
        'problem': Problem.objects.get(pk=problem_id),
    }
    if request.user.is_authenticated:
        context['current_user'] = request.user

    if request.method == 'GET':
        # Display a single problem
        return render(request, 'contests/prob-placeholder.html', context)

    elif request.method == 'POST':
        # Code Submission and Evaluation
        submission = Submission()
        submission.user = request.user
        submission.problem = Problem.objects.get(pk=problem_id)
        submission.language = request.POST['language-choice']
        submission.source_file = request.FILES['src-file']
        submission.status = 'Checking'
        submission.save()

        result = falcon.eval_submission(problem_code=submission.problem.problem_code,
                                        src_file_name=submission.source_file.name,
                                        language=submission.language)
        submission.status = context['response'] = result[0]
        submission.save()
        return render(request, 'contests/sub_response.html', context)

practice/templates/practice/practice-section.html
{% extends 'accounts/base.html' %}
{% block title %}
    Practice
{% endblock %}

{% block navbar %}
    <ul class="nav navbar-nav">
        <li><a href="{% url 'home:home' %}">Home</a></li>
        <li><a href="#">About</a></li>
        <li class="active"><a href="{% url 'practice:practice-home' %}">Practice</a></li>
        <li><a href="{% url 'contests:contests-home' %}">Contests</a></li>
    </ul>
    {% if not current_user %}
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" ><span class="glyphicon glyphicon-log-in"></span>
                    Login
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <form action="{% url 'accounts:accounts-login' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <label for="user_name">Username</label><br>
                            <input type="text" id="user_name" name="username"><br>
                            <label for="password">Password</label><br>
                            <input type="password" id="password" name="password"><br>
                            <input type="submit" name="log-in" value="Log In">
                        </form>
                  </li>
                </ul>
            </li>
        <li><a href="{% url 'accounts:accounts-create' %}"><span class="glyphicon glyphicon-grain"></span>SignUp</a></li>
        </ul>
    {% else %}
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" ><span class="glyphicon glyphicon-user"></span>
                    {{ current_user.username }}<span class="caret"></span>
                    </a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'accounts:accounts-home' %}">Profile</a></li>
                  <li><a href="{% url 'accounts:accounts-logout' %}">Logout</a></li>
                </ul>
            </li>
        </ul>
    {% endif %}
{% endblock %}


{% block body %}

    <div class="container-fluid text-center">
        <div class="row content">
            <div class="col-sm-2 sidenav">
                <p><a href="#">Motivation</a></p>
                <p><a href="#">Vision</a></p>
                <p><a href="#">Future</a></p>
                <p><a href="#">History</a></p>
            </div>
            <div class="col-sm-9 text-left">

                <h4>SwaGrader Practice</h4><br>
                {% if problems %}
                    <ul>
                        {% for each in problems %}
                            <li>
                                <a href="{% url 'practice:practice-problem' each.id %}">{{ each }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>No problems right now</p>
                {% endif %}

            </div>
            <div class="col-sm-1 sidenav">
                <div class="well">
                    <p>ADS</p>
                </div>
                <div class="well">
                    <p>ADS</p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}